modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/DynamicTreesTeam/DynamicTrees-AlexsCaves/issues"

[[mods]]
modId = "dtalexscaves"
version = "${file.jarVersion}"
displayName = "Dynamic Trees for Alex's Caves"

updateJSONURL = "https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/AlexsCaves.json?raw=true"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-alexs-caves"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Alex's Caves
'''

[[dependencies.dtalexscaves]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtalexscaves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtalexscaves]]
modId = "dynamictrees"
mandatory = true
versionRange = "[1.3.0-BETA10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtalexscaves]]
modId = "dynamictreesplus"
mandatory = false
versionRange = "[1.2.0-BETA2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtalexscaves]]
modId = "alexscaves"
mandatory = true
versionRange = "[1.1.4,)"
ordering = "AFTER"
side = "BOTH"